[plugin]
repository = "https://github.com/Ottermandias/Accountant.git"
commit = "de0fccfb917e7ac629ed3e45a584a78eb14f4d36"
owners = [
    "Ottermandias",
]
project_path = "Accountant"
changelog = "Updated for Dalamud staging."
