[plugin]
repository = "https://github.com/Ottermandias/RezPls.git"
commit = "d546718b5ef6d20432416ad0b0afb27833c06b71"
owners = [
    "Ottermandias",
]
project_path = "RezPls"
changelog = "Updated for Dalamud staging."
